### PR TITLE
Add Chat links to navbar

### PR DESCRIPTION
**Pull request by justdave**
Make it easier for people to find our chat rooms.

### CODE REVIEW

**Comment by hellcp** [comment]
If we are gonna make Discord official, maybe we could get in touch with folks behind [Discord <3 Open Source](https://discord.com/open-source) so we can get the `discord.gg/bugzilla` invite url. We should also probably do something on Matrix

**Comment by justdave** [comment]
> If we are gonna make Discord official, maybe we could get in touch with folks behind [Discord <3 Open Source](https://discord.com/open-source) so we can get the `discord.gg/bugzilla` invite url. We should also probably do something on Matrix

I like those ideas.  Can we bridge the channels between services?  As much as I hate the idea of being in a bunch of different places, I also like to make ease of access a thing. :)

**Comment by hellcp** [comment]
Yup, we absolutely can, and that goes for pretty much every service

**Comment by justdave** [comment]
I added the Matrix link since the IRC bridge with that works nicely and it's actively in use now.
The IRC bridge with Discord still doesn't quite work right, so I removed that link. If we get that working, we probably want to pursue the vanity link as suggested above before we put it back.

**Pull request merged**
